

// CODE INFO :-
// This code is generated by claude 
// This code is modified by me


import React, { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import axios from "axios";


const Login = () => {
  const [theme, setTheme] = useState(() => {
    const t = localStorage?.getItem("site-theme");
    return t || (window.matchMedia("(prefers-color-scheme: light)").matches ? "light" : "dark");
  });


  const navigate = useNavigate();
  const [showPassword, setShowPassword] = useState(false);
  const [success, setSuccess] = useState(false);
  const [rememberMe, setRememberMe] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [errors, setErrors] = useState({});
  const [formData, setFormData] = useState({ email: "", password: "" });


  useEffect(() => {
    const html = document.documentElement;
    html.classList.remove("light", "dark");
    html.classList.add(theme);
    try {
      localStorage.setItem("site-theme", theme);
    } catch {}
  }, [theme]);


  const validateForm = () => {
    const newErrors = {};
    if (!formData.email) {
      newErrors.email = "Email required";
    } else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(formData.email)) {
      newErrors.email = "Invalid email";
    }
    if (!formData.password) {
      newErrors.password = "Password required";
    } else if (formData.password.length < 3) {
      newErrors.password = "Min 3 chars";
    }
    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  
  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!validateForm()) return;
    setIsSubmitting(true);


    console.log(formData)
    // BACKEND LOGIN API :-
    axios.post("https://chat-gpt-1-szav.onrender.com/api/auth/login", 
      {
        email: formData.email,
        password: formData.password
      }, 
      {
        // SENDING COOKIES :-
        withCredentials: true
      }
    ).then((res) => {
      // LOG RESOLVED PROMISE :-
      console.log(res)
      navigate("/")
    }).catch((err) => {
      console.log(err)
    }).finally(() => {
      setIsSubmitting(false)
    })

  };


  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
  };




  return (
    <div className={theme}>
      {/* Theme Toggle */}
      <div className="fixed top-5 right-5 flex gap-2 bg-white/20 dark:bg-slate-900/70 backdrop-blur-md p-2 rounded-2xl border border-cyan-200/40 dark:border-slate-700 shadow-lg">
        <button
          onClick={() => setTheme("light")}
          className={`w-11 h-10 rounded-lg transition-all ${
            theme === "light"
              ? "bg-gradient-to-br from-blue-500 to-cyan-500 text-white shadow-lg"
              : "text-gray-500 hover:text-gray-700 dark:text-gray-400"
          }`}
          title="Light mode"
        >
          ☀️
        </button>
        <button
          onClick={() => setTheme("dark")}
          className={`w-11 h-10 rounded-lg transition-all ${
            theme === "dark"
              ? "bg-gradient-to-br from-purple-600 to-pink-500 text-white shadow-lg"
              : "text-gray-500 hover:text-gray-700 dark:text-gray-400"
          }`}
          title="Dark mode"
        >
          🌙
        </button>
      </div>

      {/* Success Toast */}
      {success && (
        <div className="fixed top-5 left-1/2 -translate-x-1/2 bg-green-500 text-white px-6 py-3 rounded-lg shadow-lg animate-bounce">
          ✓ Login successful! Redirecting...
        </div>
      )}

      {/* Main Container */}
      <div className="min-h-screen bg-gradient-to-br from-slate-500 via-cyan-400 to-slate-500 dark:from-slate-900 dark:to-slate-800 flex items-center justify-center p-6">
        <div
          onSubmit={handleSubmit}
          className="w-full max-w-md bg-white/70 dark:bg-slate-800 rounded-2xl shadow-xl dark:shadow-2xl p-8 border border-cyan-200/50 dark:border-slate-700 backdrop-blur-sm animate-in fade-in slide-in-from-bottom-4 duration-500"
        >
          {/* Header */}
          <div className="flex gap-4 items-center mb-6">
            <div className="w-12 h-12 bg-gradient-to-br from-cyan-400 to-blue-600 rounded-xl flex items-center justify-center text-white text-xl font-bold shadow-lg">
              🔐
            </div>
            <div>
              <h1 className="text-2xl font-bold text-gray-900 dark:text-white">Welcome back</h1>
              <p className="text-sm text-gray-600 dark:text-gray-400">Sign in to your account</p>
            </div>
          </div>

          {/* Email */}
          <div className="mb-4">
            <label className="block text-xs font-semibold text-gray-600 dark:text-gray-300 uppercase tracking-wide mb-2">
              Email address
            </label>
            <input
              type="email"
              name="email"
              placeholder="you@example.com"
              value={formData.email}
              onChange={handleChange}
              className="w-full px-4 py-3 bg-slate-100/80 dark:bg-slate-700 border border-cyan-200/60 dark:border-slate-600 rounded-lg text-gray-900 dark:text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-cyan-400 focus:border-transparent transition-all"
            />
            {errors.email && <p className="text-xs text-red-500 mt-1">{errors.email}</p>}
          </div>

          {/* Password */}
          <div className="mb-4">
            <label className="block text-xs font-semibold text-gray-600 dark:text-gray-300 uppercase tracking-wide mb-2">
              Password
            </label>
            <div className="relative">
              <input
                type={showPassword ? "text" : "password"}
                name="password"
                placeholder="••••••••"
                value={formData.password}
                onChange={handleChange}
                className="w-full px-4 py-3 bg-slate-100/80 dark:bg-slate-700 border border-cyan-200/60 dark:border-slate-600 rounded-lg text-gray-900 dark:text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-cyan-400 focus:border-transparent transition-all"
              />
              <button
                type="button"
                onClick={() => setShowPassword(!showPassword)}
                className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-500 hover:text-gray-700 dark:hover:text-gray-300 transition-colors"
              >
                {showPassword ? "👁️" : "👁️‍🗨️"}
              </button>
            </div>
            {errors.password && <p className="text-xs text-red-500 mt-1">{errors.password}</p>}
          </div>

          {/* Remember Me & Forgot Password */}
          <div className="flex items-center justify-between mb-6">
            <label className="flex items-center gap-2 cursor-pointer">
              <input
                type="checkbox"
                checked={rememberMe}
                onChange={(e) => setRememberMe(e.target.checked)}
                className="w-4 h-4 bg-slate-100 dark:bg-slate-700 border border-cyan-200/60 dark:border-slate-600 rounded cursor-pointer accent-cyan-500"
              />
              <span className="text-sm text-gray-600 dark:text-gray-400">Remember me</span>
            </label>
            <button
              type="button"
              onClick={() => alert("Forgot password feature")}
              className="text-sm text-blue-600 dark:text-purple-400 font-semibold hover:underline"
            >
              Forgot password?
            </button>
          </div>

          {/* Submit Button */}
          <button
            onClick={handleSubmit}
            disabled={isSubmitting}
            className="w-full bg-gradient-to-r from-blue-600 to-blue-700 hover:from-blue-700 hover:to-blue-800 dark:from-purple-600 dark:to-purple-700 dark:hover:from-purple-700 dark:hover:to-purple-800 text-white font-bold py-3 px-4 rounded-lg shadow-lg hover:shadow-xl transition-all disabled:opacity-70 disabled:cursor-not-allowed"
          >
            {isSubmitting ? "Signing in..." : "Sign in"}
          </button>

          {/* Signup Link */}
                      <p className="text-center text-sm text-gray-900 dark:text-gray-400 mt-4">
            Don't have an account?{" "}
            <button
              type="button"
              onClick={() => navigate("/register")}
              className="text-blue-600 dark:text-purple-400 font-semibold hover:underline"
            >
              Create one
            </button>
          </p>
        </div>
      </div>
    </div>
  );
};

export default Login;

