

// CODE INFO :-
// This code is generated by claude 
// This code is modified by me


import React, { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import axios from "axios";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";


const Register = () => {
  const [theme, setTheme] = useState(() => {
    const t = localStorage?.getItem("site-theme");
    return t || (window.matchMedia("(prefers-color-scheme: light)").matches ? "light" : "dark");
  });

  const navigate = useNavigate();
  const [showPassword, setShowPassword] = useState(false);
  const [showConfirm, setShowConfirm] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [errors, setErrors] = useState({});
  const [formData, setFormData] = useState({
    firstName: "",
    lastName: "",
    email: "",
    password: "",
    confirm: "",
  });

  // THEME INITIALISATION :-
  useEffect(() => {
    const html = document.documentElement;
    html.classList.remove("light", "dark");
    html.classList.add(theme);
    try {
      localStorage.setItem("site-theme", theme);
    } catch {}
  }, [theme]);

  // FORM VALIDATION :-
  const validateForm = () => {
    const newErrors = {};
    
    if (!formData.firstName.trim()) {
      newErrors.firstName = "First name required";
    }
    if (!formData.lastName.trim()) {
      newErrors.lastName = "Last name required";
    }
    if (!formData.email.trim()) {
      newErrors.email = "Email required";
    } else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(formData.email)) {
      newErrors.email = "Invalid email";
    }
    if (!formData.password) {
      newErrors.password = "Password required";
    } else if (formData.password.length < 6) {
      newErrors.password = "Min 6 chars";
    }
    if (!formData.confirm) {
      newErrors.confirm = "Confirm password required";
    } else if (formData.password !== formData.confirm) {
      newErrors.confirm = "Passwords don't match";
    }
    
    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  // SUBMIT BUTTON :-
  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!validateForm()) {
      toast.error("Please fix the errors above");
      return;
    }
    setIsSubmitting(true);

    console.log(formData)
    // BACKEND REGISTER API :-
    // ✅ ADDED ERROR HANDLING WITH TOASTIFY
    axios.post("https://chat-gpt-lyj2.onrender.com/api/auth/register", 
      {
        firstName: formData.firstName.trim(),
        lastName: formData.lastName.trim(),
        email: formData.email.trim(),
        password: formData.password,
        confirm: formData.confirm,
      }, 
      {
        // SENDING COOKIES :-
        withCredentials: true
      }
    ).then((res) => {
      // LOG RESOLVED PROMISE :-
      console.log(res)
      // ✅ SUCCESS TOAST NOTIFICATION
      toast.success("Registration successful! Redirecting to login...");
      
      setTimeout(() => {
        navigate("/login")
      }, 1500);
      
    }).catch((err) => {
      console.log(err)
      
      // ✅ ERROR HANDLING WITH SPECIFIC ERROR MESSAGES
      if (err.response?.status === 400) {
        toast.error(err.response.data?.message || "Email already exists");
      } else if (err.response?.status === 422) {
        toast.error("Invalid input. Please check your details");
      } else if (err.request && !err.response) {
        toast.error("Network error. Check your connection");
      } else {
        toast.error(err.response?.data?.message || "Registration failed. Try again");
      }
      
    }).finally(() => {
      setIsSubmitting(false)
    })

  };

  // HANDLE INPUT CHANGE :-
  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
  };

  return (
    <div className={theme}>
      {/* TOAST CONTAINER */}
      <ToastContainer
        position="top-right"
        autoClose={3000}
        hideProgressBar={false}
        newestOnTop={true}
        closeOnClick
        rtl={false}
        pauseOnFocusLoss
        draggable
        pauseOnHover
        theme={theme === "dark" ? "dark" : "light"}
      />

      {/* Theme Toggle */}
      <div className="fixed top-5 right-5 flex gap-2 bg-white/20 dark:bg-slate-900/70 backdrop-blur-md p-2 rounded-2xl border border-cyan-200/40 dark:border-slate-700 shadow-lg">
        <button
          onClick={() => setTheme("light")}
          className={`w-11 h-10 rounded-lg transition-all ${
            theme === "light"
              ? "bg-gradient-to-br from-blue-500 to-cyan-500 text-white shadow-lg"
              : "text-gray-500 hover:text-gray-700 dark:text-gray-400"
          }`}
          title="Light mode"
        >
          ☀️
        </button>
        <button
          onClick={() => setTheme("dark")}
          className={`w-11 h-10 rounded-lg transition-all ${
            theme === "dark"
              ? "bg-gradient-to-br from-purple-600 to-pink-500 text-white shadow-lg"
              : "text-gray-500 hover:text-gray-700 dark:text-gray-400"
          }`}
          title="Dark mode"
        >
          🌙
        </button>
      </div>

      {/* Main Container */}
      <div className="min-h-screen bg-gradient-to-br from-slate-500 via-cyan-400 to-slate-500 dark:from-slate-900 dark:to-slate-800 flex items-center justify-center p-6">
        <form
          onSubmit={handleSubmit}
          className="w-full max-w-md bg-white/70 dark:bg-slate-800 rounded-2xl shadow-xl dark:shadow-2xl p-8 border border-cyan-200/50 dark:border-slate-700 backdrop-blur-sm animate-in fade-in slide-in-from-bottom-4 duration-500"
        >
          {/* Header */}
          <div className="flex gap-4 items-center mb-6">
            <div className="w-12 h-12 bg-gradient-to-br from-green-400 to-blue-600 rounded-xl flex items-center justify-center text-white text-xl font-bold shadow-lg">
              ✨
            </div>
            <div>
              <h1 className="text-2xl font-bold text-gray-900 dark:text-white">Create account</h1>
              <p className="text-sm text-gray-600 dark:text-gray-400">Sign up to get started</p>
            </div>
          </div>

          {/* First & Last Name */}
          <div className="grid grid-cols-2 gap-3 mb-4">
            <div>
              <label className="block text-xs font-semibold text-gray-600 dark:text-gray-300 uppercase tracking-wide mb-2">
                First name
              </label>
              <input
                type="text"
                name="firstName"
                placeholder="John"
                value={formData.firstName}
                onChange={handleChange}
                disabled={isSubmitting}
                className="w-full px-4 py-3 bg-slate-100/80 dark:bg-slate-700 border border-cyan-200/60 dark:border-slate-600 rounded-lg text-gray-900 dark:text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-cyan-400 focus:border-transparent transition-all disabled:opacity-50"
              />
              {errors.firstName && <p className="text-xs text-red-500 mt-1">{errors.firstName}</p>}
            </div>
            <div>
              <label className="block text-xs font-semibold text-gray-600 dark:text-gray-300 uppercase tracking-wide mb-2">
                Last name
              </label>
              <input
                type="text"
                name="lastName"
                placeholder="Doe"
                value={formData.lastName}
                onChange={handleChange}
                disabled={isSubmitting}
                className="w-full px-4 py-3 bg-slate-100/80 dark:bg-slate-700 border border-cyan-200/60 dark:border-slate-600 rounded-lg text-gray-900 dark:text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-cyan-400 focus:border-transparent transition-all disabled:opacity-50"
              />
              {errors.lastName && <p className="text-xs text-red-500 mt-1">{errors.lastName}</p>}
            </div>
          </div>

          {/* Email */}
          <div className="mb-4">
            <label className="block text-xs font-semibold text-gray-600 dark:text-gray-300 uppercase tracking-wide mb-2">
              Email address
            </label>
            <input
              type="email"
              name="email"
              placeholder="you@example.com"
              value={formData.email}
              onChange={handleChange}
              disabled={isSubmitting}
              className="w-full px-4 py-3 bg-slate-100/80 dark:bg-slate-700 border border-cyan-200/60 dark:border-slate-600 rounded-lg text-gray-900 dark:text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-cyan-400 focus:border-transparent transition-all disabled:opacity-50"
            />
            {errors.email && <p className="text-xs text-red-500 mt-1">{errors.email}</p>}
          </div>

          {/* Password */}
          <div className="mb-4">
            <label className="block text-xs font-semibold text-gray-600 dark:text-gray-300 uppercase tracking-wide mb-2">
              Password
            </label>
            <div className="relative">
              <input
                type={showPassword ? "text" : "password"}
                name="password"
                placeholder="••••••••"
                value={formData.password}
                onChange={handleChange}
                disabled={isSubmitting}
                className="w-full px-4 py-3 bg-slate-100/80 dark:bg-slate-700 border border-cyan-200/60 dark:border-slate-600 rounded-lg text-gray-900 dark:text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-cyan-400 focus:border-transparent transition-all disabled:opacity-50"
              />
              <button
                type="button"
                onClick={() => setShowPassword(!showPassword)}
                disabled={isSubmitting}
                className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-500 hover:text-gray-700 dark:hover:text-gray-300 transition-colors disabled:opacity-50"
              >
                {showPassword ? "👁️" : "👁️‍🗨️"}
              </button>
            </div>
            {errors.password && <p className="text-xs text-red-500 mt-1">{errors.password}</p>}
          </div>

          {/* Confirm Password */}
          <div className="mb-6">
            <label className="block text-xs font-semibold text-gray-600 dark:text-gray-300 uppercase tracking-wide mb-2">
              Confirm password
            </label>
            <div className="relative">
              <input
                type={showConfirm ? "text" : "password"}
                name="confirm"
                placeholder="••••••••"
                value={formData.confirm}
                onChange={handleChange}
                disabled={isSubmitting}
                className="w-full px-4 py-3 bg-slate-100/80 dark:bg-slate-700 border border-cyan-200/60 dark:border-slate-600 rounded-lg text-gray-900 dark:text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-cyan-400 focus:border-transparent transition-all disabled:opacity-50"
              />
              <button
                type="button"
                onClick={() => setShowConfirm(!showConfirm)}
                disabled={isSubmitting}
                className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-500 hover:text-gray-700 dark:hover:text-gray-300 transition-colors disabled:opacity-50"
              >
                {showConfirm ? "👁️" : "👁️‍🗨️"}
              </button>
            </div>
            {errors.confirm && <p className="text-xs text-red-500 mt-1">{errors.confirm}</p>}
          </div>

          {/* Submit Button */}
          <button
            type="submit"
            disabled={isSubmitting}
            className="w-full bg-gradient-to-r from-green-600 to-green-700 hover:from-green-700 hover:to-green-800 dark:from-purple-600 dark:to-purple-700 dark:hover:from-purple-700 dark:hover:to-purple-800 text-white font-bold py-3 px-4 rounded-lg shadow-lg hover:shadow-xl transition-all disabled:opacity-70 disabled:cursor-not-allowed"
          >
            {isSubmitting ? "Creating account..." : "Create account"}
          </button>

          {/* Login Link */}
          <p className="text-center text-sm text-gray-900 dark:text-gray-400 mt-4">
            Already have an account?{" "}
            <button
              type="button"
              onClick={() => navigate("/login")}
              disabled={isSubmitting}
              className="text-blue-600 dark:text-purple-400 font-semibold hover:underline disabled:opacity-50"
            >
              Login here
            </button>
          </p>
        </form>
      </div>
    </div>
  );
};

export default Register;




